# docker stack deploy -c intranet.yml --prune intranet
version: "3.7"
services:
  dmz:
    image: traefik:v2.2
    command:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false

      - --accesslog
      - --accesslog.fields.headers.defaultmode=keep
      - --api
      - --ping

      - --entrypoints.http.address=:80
      - --entrypoints.http.http.middlewares=compress-all@file
      - --entryPoints.http.forwardedHeaders.insecure

      - --providers.docker.endpoint=tcp://daemon:2375
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.network=intranet
      - "--providers.docker.constraints=Label(`intranet`, `true`)"
      - '--providers.docker.defaultrule=Host(`i.trajano.net`) && PathPrefix(`/{{ .Name | trimPrefix (index .Labels "com.docker.stack.namespace") | trimPrefix "_" | trimPrefix "-" }}`)'

      - --providers.file.filename=/traefik-conf.toml

      - --tracing.zipkin.httpEndpoint=http://zipkin:9411/api/v2/spans
      - --tracing.serviceName=i-traefik
    healthcheck:
      test: traefik healthcheck --ping
    labels:
      co.elastic.logs/module: traefik
      co.elastic.logs/fileset.stdout: access
      co.elastic.logs/fileset.stderr: error
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          memory: 64M
          cpus: "1.0"
        reservations:
          memory: 16M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik

        - traefik.http.routers.intranet.rule=Host(`i.trajano.net`)
        - traefik.http.routers.intranet.entrypoints=https
        - traefik.http.routers.intranet.tls.options=intranet@file
        - traefik.http.routers.intranet.tls.certresolver=default
        - traefik.http.routers.intranet.service=intranet
        - traefik.http.services.intranet.loadbalancer.server.port=80
    volumes:
      - /d/p/trajano.net/traefik.toml:/traefik-conf.toml
    networks:
      - intranet
      - traefik
      - internal
      - management
  daemon:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
    environment:
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    labels:
      - co.elastic.logs/enabled=false
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
  ping:
    image: alpine/socat
    command: tcp-listen:8080,fork,reuseaddr tcp:proxy:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
      labels:
        - intranet=true
        - traefik.enable=true
        - traefik.http.routers.ping.rule=Path(`/ping`)
        - traefik.http.routers.ping.service=ping
        - traefik.http.services.ping.loadbalancer.server.port=8080

        - traefik.http.routers.traefik.rule=(PathPrefix(`/traefik`) || PathPrefix(`/api`))
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.middlewares=traefik-strip
        - traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik
    networks:
      - intranet
  whoami:
    image: containous/whoami
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
      labels:
        - intranet=true
        - traefik.enable=true
        - traefik.http.routers.whoami.middlewares=strip-prefix@file
        - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - intranet
  # db:
  #   image: mysql:8
  #   environment:
  #     MYSQL_DATABASE: admin
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_ROOT_HOST: db.trajano.net
  #   networks:
  #     - traefik
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.docker.network=traefik
  #       - traefik.tcp.routers.db.rule=HostSNI(`db.trajano.net`)
  #       - traefik.tcp.routers.db.entrypoints=https
  #       - traefik.tcp.routers.db.tls.options=intranet@file
  #       - traefik.tcp.routers.db.tls.certresolver=default
  #       - traefik.tcp.routers.db.tls.passthrough=false
  #       - traefik.tcp.routers.db.service=db
  #       - traefik.tcp.services.db.loadbalancer.server.port=3306
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password1
  #   networks:
  #     - traefik
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.docker.network=traefik
  #       - traefik.tcp.routers.db.rule=HostSNI(`db.trajano.net`)
  #       - traefik.tcp.routers.db.entrypoints=https
  #       - traefik.tcp.routers.db.tls.options=intranet@file
  #       - traefik.tcp.routers.db.tls.certresolver=default
  #       - traefik.tcp.routers.db.service=db
  #       - traefik.tcp.services.db.loadbalancer.server.port=5432
networks:
  traefik:
    external: true
  intranet:
    external: true
  management:
    external: true
  internal:
    internal: true
    attachable: false
