# docker stack deploy -c management.yml --prune management
version: "3.7"
services:
  zipkin:
    image: openzipkin/zipkin:2.21.1
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    networks:
      - management
      - management-ui
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
      - "logger.org.elasticsearch=error"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/module: elasticsearch
      co.elastic.logs/fileset.stdout: server
    deploy:
      resources:
        limits:
          memory: 1G
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - management-ui
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    deploy:
      mode: global
    command:
      - -E
      - |
        filebeat.autodiscover.providers=[
          {
            type: docker,
            hints.enabled: true
          }
        ]
      - -E
      - processors={1:{add_docker_metadata:{host:unix:///var/run/docker.sock}}}
      - -E
      - output.elasticsearch.enabled=true
      - -E
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - -E
      - output.logstash.enabled=false
      - --modules
      - nginx,mysql,system,traefik,kibana,logstash
      # - -d
      # - autodiscover
      # - -e
    user: root
    labels:
      co.elastic.logs/enabled: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.6.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    user: root
    hostname: "{{.Node.Hostname}}"
    command:
      - -E
      - |
        metricbeat.modules=[
          {
            module:docker,
            hosts:[unix:///var/run/docker.sock],
            period:10s,
            enabled:true
          }
        ]
      - -E
      - processors={1:{add_docker_metadata:{host:unix:///var/run/docker.sock}}}
      - -E
      - output.elasticsearch.enabled=true
      - -E
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - -E
      - output.logstash.enabled=false
    deploy:
      mode: global
  kibana-api:
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
      - LOGGING_SILENT=true
    networks:
      - default
      - management-ui
    deploy:
      labels:
        co.elastic.logs/module: kibana
        co.elastic.logs/fileset: log

networks:
  management:
    name: management
    internal: true
    attachable: true
  management-ui:
    name: management-ui
    internal: true
    attachable: true
  default:
    internal: true
    attachable: true
volumes:
  elasticsearch-data:
